version: "3.8"

services:
  test_postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ismp_test
      POSTGRES_USER: ismp
      POSTGRES_PASSWORD: "test"

  test_backend:
    image: "localhost/ismp/backend:snapshot"
    environment: &TEST_BACKEND_ENV
      DEBUG: 'FALSE'
      DB_DATABASE: ismp_test
      DB_HOST: test_postgres
      DB_PASSWORD: "test"
      DB_PORT: 5432
      DB_USER: ismp
      USE_S3: "FALSE"
      USE_MAILCHIMP: "FALSE"
      DJANGO_SECRET_KEY: "this_is_not_a_real_secret_key"
    depends_on:
      - backend
      - test_postgres
    command: /app/api/run_tests.sh

  test_backend_migrations:
    image: "localhost/ismp/backend:snapshot"
    volumes:
      - ./backend:/app/api
    environment:
      <<: *TEST_BACKEND_ENV
    command: /app/api/run_migrations.sh
    depends_on:
      - test_postgres
      - test_backend

  test_frontend:
    image: "localhost/ismp/frontend:snapshot"
    environment:
      REACT_APP_API_HOST: "http://test_backend:8000"
      USE_S3: "FALSE"
    depends_on:
      - frontend
      - test_backend
      - test_backend_migrations
    command: /bin/sh -c "yarn run lint && yarn test"
