version: "3.8"

services:
  frontend:
    image: "localhost/ismp/frontend:snapshot"
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    environment:
      REACT_APP_AWS_STORAGE_BUCKET_NAME:
    volumes: []
