version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ismp
      POSTGRES_USER: ismp
      POSTGRES_PASSWORD: "password"

  backend:
    # docker-compose will build an image called "localhost/ismp/backend:snapshot"
    build: ./backend
    image: "localhost/ismp/backend:snapshot"
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"
    environment: &BACKEND_ENV
      USE_S3: "FALSE"
      AWS_ACCESS_KEY_ID: "foobar_key"
      AWS_SECRET_ACCESS_KEY: "foobar_secret"
      AWS_STORAGE_BUCKET_NAME: "fake_bucket_lalala"
      USE_MAILCHIMP: 'FALSE'
      MAILCHIMP_USERNAME: 'foobar'
      MAILCHIMP_API_KEY: 'foobar_api_key'
      MAILCHIMP_LIST_ID: 'foobar_list_id'
      ALLOWED_HOST: ''
      DB_DATABASE: ismp
      DB_HOST: postgres
      DB_PASSWORD: "password"
      DB_PORT: 5432
      DB_USER: ismp
      DEBUG: "TRUE"
      # this is not the key that will be used in production. Also please note
      # that in environment variables in docker-compose.yml, you have to
      # escape the $ character with another $ ($$).
      DJANGO_SECRET_KEY: "this_is_not_a_real_secret_key"
    depends_on:
      - postgres

  backend_migrations:
    image: "localhost/ismp/backend:snapshot"
    volumes:
      - ./backend:/app/api
    environment:
      <<: *BACKEND_ENV
    command: /app/api/run_migrations.sh
    depends_on:
      - postgres
      - backend # `backend` will build the image used for `backend_migrations`

  frontend:
    # docker-compose will build an image called "localhost/ismp/frontend:snapshot"
    image: "localhost/ismp/frontend:snapshot"
    build: ./frontend
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_HOST: "http://backend:8000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
