version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-and-test:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/install-docker-tools
      - run:
          name: Test
          command: |
            .circleci/test_backend.sh
  build-and-publish:
    environment:
      IMAGE_BEND: richyen/ismp-backend
      IMAGE_FEND: richyen/ismp-frontend
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image and push
          command: |
            make build
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_BEND:latest
            docker push $IMAGE_FEND:latest


workflows:
  main:
    jobs:
      - build-and-test
      - build-and-publish:
          context: ismp_website
          filters:
            branches:
              only: master
