---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Something
- type: document
  path: frontend/public/locales/en/home.json
  label: Home Page
- type: document
  path: "\\frontend\\public\\locales"
  label: Webinar
upload_dir: krikor-cms-test
public_path: https://ismp-us-east-1.s3.amazonaws.com/krikor-cms-test
front_matter_path: ''
use_front_matter_path: 
file_template: 'media/:filename:'
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
