---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: frontend\public\locales\en\home.json
  label: Home Page
  match: "**/*"
- type: directory
  path: ''
  label: Stuff
  create: all
  match: "**/*"
- type: document
  path: "\\frontend\\public\\locales"
  label: Webinar
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: 'forestry/:filename:'
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
