name: CI

on:
  # Run on all commits to master branch
  push:
    branches:
      - master
  # Run on all pull requests to master branch
  pull_request:
    branches:
      - master

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make-test
      run: |
        ./.github/workflows/test_backend.sh
