name: CI

on:
  # Run on all commits to master branch
  push:
    branches:
      - master
  # Run on all pull requests to master branch
  pull_request:
    branches:
      - master

jobs:
  test_frontend:
    name: 'test_frontend'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: International-Mentorship-ISMP/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: 'Check for changes in Git'
        id: changes
        run: |
          if git diff --quiet HEAD master -- frontend ; then
            echo "::set-output name=frontend::yes"
          else
            echo "::set-output name=frontend::no"
          fi

      - name: 'Run Frontend Tests'
        if: (github.ref == 'refs/heads/master') || (steps.changes.outputs.frontend == 'yes')
        run: make test_frontend

  build_and_publish:
    name: 'build_and_publish'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: 'Checkout'
        uses: International-Mentorship-ISMP/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: 'Check for changes in Git'
        id: changes
        run: |
          if git diff --quiet HEAD master -- backend ; then
            echo "::set-output name=backend::yes"
          else
            echo "::set-output name=backend::no"
          fi

      - name: 'Build images'
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml build

      - name: 'Run Backend Tests'
        if: (github.ref == 'refs/heads/master') || (steps.changes.outputs.backend == 'yes')
        run: make test_backend

      - name: 'Run Simple Integration Test'
        run: ./run_integration_test.sh

      - name: 'Show docker-compose logs if there are any failures'
        if: failure()
        run: docker-compose logs --tail=200

      - name: 'Tag and Publish'
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN_ISMP }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER_ISMP }}
        run: |
          # Login to Docker Hub
          echo ${DOCKER_HUB_TOKEN} | docker login -u ${DOCKER_HUB_USER} --password-stdin

          # Tag and Publish Backend
          docker tag localhost/ismp/backend:snapshot docker.io/ismp/backend:${GITHUB_SHA}
          docker tag localhost/ismp/backend:snapshot docker.io/ismp/backend:latest
          docker push docker.io/ismp/backend:${GITHUB_SHA}
          docker push docker.io/ismp/backend:latest

          # Tag and Publish Frontend
          docker tag localhost/ismp/frontend:snapshot docker.io/ismp/frontend:${GITHUB_SHA}
          docker tag localhost/ismp/frontend:snapshot docker.io/ismp/frontend:latest
          docker push docker.io/ismp/frontend:${GITHUB_SHA}
          docker push docker.io/ismp/frontend:latest

          # Remove docker config file just in case, for security reasons
          sudo rm -rf /home/runner/.docker/config.json

      - name: 'Queue up a Terraform run to Deploy Backend'
        if: github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
          IMAGE_TAG_VAR: ${{ secrets.BACKEND_IMAGE_TAG_TFE_VARIABLE_ID }}
          TFE_WS_ID: $${ secrets.TFE_BACKEND_WORKSPACE_ID }}
        run: |
          aws lambda invoke \
          --function-name tfe_set_image_tag \
          --invocation-type Event \
          --payload '{"tfe_image_tag_variable": "${IMAGE_TAG_VAR}","tfe_workspace_id": ${TFE_WS_ID},"repository":"backend","version": "${GITHUB_SHA}"}' \
          response.json

      - name: 'Queue up a Terraform run to Deploy Frontend'
        if: github.ref == 'refs/heads/master'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
          IMAGE_TAG_VAR: ${{ secrets.FRONTEND_IMAGE_TAG_TFE_VARIABLE_ID }}
          TFE_WS_ID: $${ secrets.TFE_FRONTEND_WORKSPACE_ID }}
        run: |
          aws lambda invoke \
          --function-name tfe_set_image_tag \
          --invocation-type Event \
          --payload '{"tfe_image_tag_variable": "${IMAGE_TAG_VAR}","tfe_workspace_id": ${TFE_WS_ID},"repository":"frontend","version": "${GITHUB_SHA}"}' \
          response.json
